src/modules/Toml/CMakeLists.txt, src/modules/Toml/src/TomlUtility.F90, src/submodules/Toml/CMakeLists.txt, src/submodules/Toml/src/TomlUtility@GetMethods.F90
=> Toml support in easifem

src/modules/AbstractBC/CMakeLists.txt, src/modules/AbstractBC/src/AbstractBC.toml, src/modules/AbstractBC/src/AbstractBC_Class.F90, src/submodules/AbstractBC/src/AbstractBC_Class@ConstructorMethods.F90, src/submodules/AbstractBC/src/AbstractBC_Class@GetMethods.F90, src/submodules/AbstractBC/src/AbstractBC_Class@IOMethods.F90, src/submodules/AbstractBC/src/AbstractBC_Class@SetMethods.F90
=> Enhancements in AbstractBoundaryCondition_

src/modules/DirichletBC/src/DirichletBC_Class.F90, src/submodules/DirichletBC/src/DirichletBC_Class@ConstructorMethods.F90, src/submodules/DirichletBC/src/DirichletBC_Class@GetMethods.F90, src/submodules/DirichletBC/src/DirichletBC_Class@IOMethods.F90
=> Enhancements in DirichletBC_

src/modules/Fhash/CMakeLists.txt, src/modules/Fhash/src/fhash.F90, src/modules/Fhash/src/fhash_data_container.F90, src/modules/Fhash/src/fhash_fnv.F90, src/modules/Fhash/src/fhash_key/base.F90, src/modules/Fhash/src/fhash_key/char.F90, src/modules/Fhash/src/fhash_key/int32.F90, src/modules/Fhash/src/fhash_key/int32_1d.F90, src/modules/Fhash/src/fhash_key/int64.F90, src/modules/Fhash/src/fhash_key/int64_1d.F90, src/modules/Fhash/src/fhash_sll.F90, src/modules/Fhash/src/fhash_tbl.F90, src/modules/Fhash/src/fhash_tbl_iter.F90
=> Hash-table support in easifem

src/modules/AbstractFE/src/AbstractFE_Class.F90, src/modules/FiniteElement/src/FiniteElement_Class.F90, src/submodules/FiniteElement/src/FiniteElement_Class@Methods.F90
=> Enhancements in Finite Element

src/modules/GmshAPI/src/NoGmsh/Gmsh_Class.F90
=> Build error when USE_GMSH_SDK off

src/modules/ftlMacros/ftlPointerVector.inc
=> Fixing ftlPointerVector

src/submodules/STScalarField/src/STScalarField_Class@ConstructorMethods.F90
=> Fixes issue #194

cmake/Modules/FindGmsh.cmake, src/submodules/STScalarField/src/STScalarField_Class@ConstructorMethods.F90
=> Fixes FindGmsh and Issue #194

src/modules/ScalarField/src/ScalarField_Class.F90, src/submodules/STScalarField/src/STScalarField_Class@ConstructorMethods.F90, src/submodules/ScalarField/src/ScalarField_Class@ConstructorMethods.F90
- Removing sField_Initiate_old method
- Removing bug from stsField_Initiate1 method
Fixes issue #199
=> Update in STScalarField_

dprint.json, src/modules/AbstractBC/src/AbstractBC.toml, src/modules/AbstractBC/src/AbstractBC_Class.F90, src/modules/UserFunction/src/UseFunction.toml, src/modules/UserFunction/src/UserFunction_Class.F90, src/submodules/AbstractBC/src/AbstractBC_Class@ConstructorMethods.F90, src/submodules/AbstractBC/src/AbstractBC_Class@GetMethods.F90, src/submodules/AbstractBC/src/AbstractBC_Class@IOMethods.F90, src/submodules/AbstractBC/src/AbstractBC_Class@SetMethods.F90, src/submodules/Domain/src/Domain_Class@GetMethods.F90, src/submodules/MeshSelection/src/MeshSelection_Class@GetNodeNumMethods.F90, src/submodules/UserFunction/src/UserFunction_Class@ConstructorMethods.F90, src/submodules/UserFunction/src/UserFunction_Class@IOMethods.F90
- Adding UserFunction in AbstractBC, fixes issue #205
- Updates in UserFunction ImportFromToml method
- Update in MeshSelection, GetNodeNum method
- Update in Domain_Class
=> Adding UserFunction in AbstractBC

src/modules/AbstractMaterialModel/src/AbstractMaterialModel_Class.F90, src/modules/CMakeLists.txt, src/submodules/CMakeLists.txt
Fixing issue #217 caused due to the merging easifemMaterial lib to easifemClasses.
=> Fixing issue #217

src/modules/AbstractBC/src/AbstractBC_Class.F90, src/submodules/LinearPoroElasticModel/src/LinearPoroElasticModel_Class@GetMethods.F90, src/submodules/NewtonianFluidModel/src/NewtonianFluidModel_Class@GetMethods.F90, src/submodules/NewtonianFluidModel/src/NewtonianFluidModel_Class@SetMethods.F90
In set method instead of pointer we now add target.
=> Update in AbstractBC_Class 

src/modules/AbstractNodeField/src/AbstractNodeField_Class.F90, src/submodules/AbstractNodeField/src/AbstractNodeField_Class@GetMethods.F90
=> Enhancement in AbstractNodeField

src/modules/AbstractSolidMechanicsModel/src/AbstractSolidMechanicsModel_Class.F90, src/submodules/AbstractSolidMechanicsModel/CMakeLists.txt, src/submodules/AbstractSolidMechanicsModel/src/AbstractSolidMechanicsModel_Class@ConstructorMethods.F90, src/submodules/AbstractSolidMechanicsModel/src/AbstractSolidMechanicsModel_Class@GetMethods.F90, src/submodules/AbstractSolidMechanicsModel/src/AbstractSolidMechanicsModel_Class@IOMethods.F90, src/submodules/AbstractSolidMechanicsModel/src/AbstractSolidMechanicsModel_Class@SetMethods.F90
Adding new module structure in AbstractSolidMechanicsModel
=> Updates in AbstractSolidMechanicsModel

src/modules/AbstractMaterialModel/src/AbstractMaterialModel_Class.F90, src/submodules/AbstractMaterialModel/CMakeLists.txt, src/submodules/AbstractMaterialModel/src/AbstractMaterialModel_Class@ConstructorMethods.F90, src/submodules/AbstractMaterialModel/src/AbstractMaterialModel_Class@GetMethods.F90, src/submodules/AbstractMaterialModel/src/AbstractMaterialModel_Class@IOMethods.F90, src/submodules/AbstractMaterialModel/src/AbstractMaterialModel_Class@SetMethods.F90, src/submodules/CMakeLists.txt
Updates in AbstractMaterialmodel Class, related to new material model API.
=> Updates in AbstractMaterialModel class

src/modules/STScalarField/src/STScalarField_Class.F90, src/submodules/STScalarField/src/STScalarField_Class@DBCMethods.F90
=> Updates in STScalarField_Class

src/modules/LinearElasticModel/src/LinearElasticModel_Class.F90, src/submodules/LinearElasticModel/src/LinearElasticModel_Class@ConstructorMethods.F90, src/submodules/LinearElasticModel/src/LinearElasticModel_Class@IOMethods.F90
Working towards new api for material model. This is still work in progress.
=> Updates in LinearElasticModel

src/modules/AbstractPoroMechanicsModel/src/AbstractPoroMechanicsModel_Class.F90, src/submodules/LinearPoroElasticModel/src/LinearPoroElasticModel_Class@ConstructorMethods.F90, src/submodules/LinearPoroElasticModel/src/LinearPoroElasticModel_Class@IOMethods.F90
Working towards new api for material models
=> Updates in Poroelastic material models

src/submodules/AbstractNodeField/src/AbstractNodeField_Class@SetMethods.F90, src/submodules/ScalarField/src/ScalarField_Class@SetMethods.F90
=> Updates in ScalarField

src/modules/CMakeLists.txt, src/modules/LinearElasticModel/src/LinearElasticModel_Class.F90, src/modules/LinearPoroElasticModel/src/LinearPoroElasticModel_Class.F90, src/modules/SolidMechanicsModel/CMakeLists.txt, src/modules/SolidMechanicsModel/src/SolidMechanicsModelUtility.F90, src/modules/easifemMaterials/src/easifemMaterials.F90, src/submodules/LinearElasticModel/src/LinearElasticModel_Class@ConstructorMethods.F90, src/submodules/LinearElasticModel/src/LinearElasticModel_Class@GetMethods.F90
Working on features #212 and #233
=> Updates in easifemMaterials

src/modules/AbstractSolidMechanicsModel/src/AbstractSolidMechanicsModel_Class.F90, src/modules/LinearElasticModel/src/LinearElasticModel.toml, src/modules/LinearElasticModel/src/LinearElasticModel_Class.F90, src/modules/SolidMechanicsModel/src/SolidMechanicsModelUtility.F90, src/submodules/AbstractMaterialModel/src/AbstractMaterialModel_Class@IOMethods.F90, src/submodules/AbstractSolidMechanicsModel/src/AbstractSolidMechanicsModel_Class@IOMethods.F90, src/submodules/LinearElasticModel/src/LinearElasticModel_Class@ConstructorMethods.F90, src/submodules/LinearElasticModel/src/LinearElasticModel_Class@IOMethods.F90
Adding toml-support in LinearElasticModel. Fixes issue and feature #233 #212
=> Adding toml-supports in LinearElasticModel

src/modules/SolidMaterial/src/SolidMaterial_Class.F90, src/submodules/SolidMaterial/src/SolidMaterial_Class@ConstructorMethods.F90, src/submodules/SolidMaterial/src/SolidMaterial_Class@GetMethods.F90, src/submodules/SolidMaterial/src/SolidMaterial_Class@IOMethods.F90, src/submodules/SolidMaterial/src/SolidMaterial_Class@SetMethods.F90
Changing the naming convention of private methods.
=> Updates in SolidMaterial_Class

src/modules/SolidMaterial/src/SolidMaterial_Class.F90, src/submodules/SolidMaterial/src/SolidMaterial_Class@IOMethods.F90
=> Updates in SolidMaterials

src/submodules/STScalarField/src/STScalarField_Class@SetMethods.F90
=> Updates in STScalarField

src/modules/AbstractMaterial/src/AbstractMaterial.toml, src/modules/AbstractMaterial/src/AbstractMaterial_Class.F90, src/modules/Toml/src/TomlUtility.F90, src/modules/UserFunction/src/UseFunction.toml, src/submodules/AbstractMaterial/src/AbstractMaterial_Class@IOMethods.F90, src/submodules/Toml/src/TomlUtility@GetMethods.F90
- Enhancements in abstractMaterial related to `importFromToml`
- Working towards feature #212
=> Updates in AbstractMaterial

src/modules/AbstractKernel/CMakeLists.txt, src/modules/AbstractKernel/src/AbstractKernelParam.F90, src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/modules/CMakeLists.txt, src/modules/FiniteElement/src/FiniteElement_Class.F90, src/modules/easifemKernels/CMakeLists.txt, src/modules/easifemKernels/src/easifemKernels.F90, src/submodules/AbstractKernel/CMakeLists.txt, src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleRHSMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleTanmatMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConstructorMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConvergenceMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@GetMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@IOMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@InitiateFieldsMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@RunMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@SetMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@SolveMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@UpdateMethods.F90, src/submodules/CMakeLists.txt, src/submodules/MaterialFactory/src/MaterialFactory@Methods.F90
- Fixes issue #250
- Merging kernels to classes
=> Merging easifemKernels into easifemClasses

src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleRHSMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleTanmatMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConstructorMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConvergenceMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@GetMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@IOMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@InitiateFieldsMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@RunMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@SetMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@SolveMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@UpdateMethods.F90
- Changing names of private methods
=> Updating private routine name in kernels

src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/modules/FPL/src/FPL_Method.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleRHSMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleTanmatMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConstructorMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConvergenceMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@IOMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@SolveMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@UpdateMethods.F90
- Enhancing kernels
- Adding toml-support
=> Updates on Kernels

src/modules/DirichletBC/src/DirichletBC_Class.F90, src/modules/NeumannBC/src/NeumannBC_Class.F90, src/modules/NitscheBC/src/NitscheBC_Class.F90, src/submodules/DirichletBC/src/DirichletBC_Class@IOMethods.F90, src/submodules/NeumannBC/src/NeumannBC_Class@IOMethods.F90, src/submodules/NitscheBC/src/NitscheBC_Class@IOMethods.F90
- Enhancing display method in boundary condition
- Now display works for vector of `DirichletBC_`, `NitscheBC_`, and `NeumannBC_`
- Now display work for vector of boundary condition pointer
=> Updates in boundary condition

src/modules/AbstractKernel/src/AbstractKernelParam.F90, src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/modules/DomainConnectivity/src/DomainConnectivity_Class.F90, src/submodules/AbstractKernel/CMakeLists.txt, src/submodules/AbstractKernel/src/AbstractKernel_Class@BCMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConstructorMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@IOMethods.F90
=> Adding boundary condition to AbstractKernel

src/modules/AbstractKernel/src/AbstractKernelParam.F90, src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/modules/AbstractMeshField/src/AbstractMeshField_Class.F90, src/modules/MeshSelection/src/MeshSelection_Class.F90, src/modules/SolidMaterial/src/SolidMaterial_Class.F90, src/submodules/AbstractKernel/CMakeLists.txt, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConstructorMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@MaterialMethods.F90
=> Updates in Kernels

src/modules/UserFunction/src/UserFunction_Class.F90, src/submodules/UserFunction/src/UserFunction_Class@ConstructorMethods.F90, src/submodules/UserFunction/src/UserFunction_Class@GetMethods.F90, src/submodules/UserFunction/src/UserFunction_Class@IOMethods.F90
Updates in UserFunction class, fixes #267 
- Adding Get method for getting FEVariable 
- Minor formatting
=> Updates in UserFunction

src/modules/ScalarMeshField/src/ScalarMeshField_Class.F90, src/submodules/ScalarMeshField/src/ScalarMeshField_Class@ConstructorMethods.F90
- Working on feature #262
- Construct from `UserFunction` and `AbstractMaterial` is now possible
- Set values by using `UserFunction` is possible.
=> Updates in ScalarMeshField

src/modules/STScalarMeshField/src/STScalarMeshField_Class.F90, src/modules/STTensorMeshField/src/STTensorMeshField_Class.F90, src/modules/STVectorMeshField/src/STVectorMeshField_Class.F90, src/modules/TensorMeshField/src/TensorMeshField_Class.F90, src/modules/VectorMeshField/src/VectorMeshField_Class.F90, src/submodules/STScalarMeshField/src/STScalarMeshField_Class@ConstructorMethods.F90, src/submodules/STTensorMeshField/src/STTensorMeshField_Class@ConstructorMethods.F90, src/submodules/STVectorMeshField/src/STVectorMeshField_Class@ConstructorMethods.F90, src/submodules/TensorMeshField/src/TensorMeshField_Class@ConstructorMethods.F90, src/submodules/VectorMeshField/src/VectorMeshField_Class@ConstructorMethods.F90
- Working on feature #262
- Construct from `UserFunction` and `AbstractMaterial` is now possible
- Set values by using `UserFunction` is possible.
=> Updates in MeshField

src/modules/STVectorField/src/STVectorField_Class.F90, src/submodules/STVectorField/src/STVectorField_Class@DBCMethods.F90
=> Update DBC methods in STVectorField

src/modules/STVectorField/src/STVectorField_Class.F90, src/submodules/STVectorField/src/STVectorField_Class@SetMethods.F90
- fixing the issue #288
- add 2 new set methods; `Set16` and `Set17`
- change the handling way of `addContribution`
=> Updates Set method in STVectorField

src/modules/AbstractFE/src/AbstractFE_Class.F90, src/modules/RefElement/src/AbstractRefElement_Class.F90, src/modules/RefElement/src/RefHexahedron_Class.F90, src/submodules/AbstractFE/src/AbstractFE_Class@ConstructorMethods.F90, src/submodules/AbstractFE/src/AbstractFE_Class@DGMethods.F90, src/submodules/AbstractFE/src/AbstractFE_Class@GetMethods.F90, src/submodules/AbstractFE/src/AbstractFE_Class@H1Methods.F90, src/submodules/AbstractFE/src/AbstractFE_Class@HCurlMethods.F90, src/submodules/AbstractFE/src/AbstractFE_Class@HDivMethods.F90, src/submodules/AbstractFE/src/AbstractFE_Class@IOMethods.F90, src/submodules/AbstractFE/src/AbstractFE_Class@QuadratureMethods.F90, src/submodules/AbstractFE/src/AbstractFE_Class@SetMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@SetMethods.F90, src/submodules/FiniteElement/src/FiniteElement_Class@ConstructorMethods.F90, src/submodules/RefElement/src/AbstractRefElement_Class@Methods.F90, src/submodules/RefElement/src/RefHexahedron_Class@Methods.F90, src/submodules/RefElement/src/RefLine_Class@Methods.F90, src/submodules/RefElement/src/RefPrism_Class@Methods.F90, src/submodules/RefElement/src/RefPyramid_Class@Methods.F90, src/submodules/RefElement/src/RefQuadrangle_Class@Methods.F90, src/submodules/RefElement/src/RefTetrahedron_Class@Methods.F90, src/submodules/RefElement/src/RefTriangle_Class@Methods.F90
- Major updates in Finite element 
- Fixes issue #293, issue #291
=> Updates in FiniteElement

src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/modules/AbstractKernel/src/KernelUtility.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleTanmatMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConstructorMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@InitiateFieldsMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@MaterialMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@SetMethods.F90
- Working on Enhancements of AbstractKernels
- Some improvements are needed in SolidMaterial
=> Updates in AbstractKernels

src/submodules/LinSolver/src/LinSolver_Class@GetMethods.F90
=> Updates in GetLinSolverCodeFromName

src/modules/FieldFactory/src/FieldFactory.F90, src/submodules/FieldFactory/src/FieldFactory@NodeFieldFactoryMethods.F90
- fixing the issue #301
- add module routines to initiate STScalarField and STVectorField
=> Updates in NodeFieldFactoryMethods of FieldFactory

src/modules/AbstractNodeField/src/AbstractNodeField_Class.F90, src/modules/BlockNodeField/src/BlockNodeField_Class.F90, src/modules/BlockNodeFieldLis/src/BlockNodeFieldLis_Class.F90, src/modules/STScalarField/src/STScalarField_Class.F90, src/modules/STVectorField/src/STVectorField_Class.F90, src/modules/ScalarField/src/ScalarField_Class.F90, src/modules/VectorField/src/VectorField_Class.F90, src/submodules/BlockNodeField/src/BlockNodeField_Class@DBCMethods.F90
- Updating ApplyDBC in BlockNodeField
=> Updates in NodeField

src/modules/UserFunction/src/UserFunction_Class.F90, src/submodules/UserFunction/src/UserFunction_Class@GetMethods.F90
- Adding GetVectorValue method which does not allocate data.
=> Updates in UserFunction_Class

src/modules/AbstractNodeField/src/AbstractNodeField_Class.F90, src/modules/STScalarField/src/STScalarField_Class.F90, src/modules/STVectorField/src/STVectorField_Class.F90, src/modules/ScalarField/src/ScalarField_Class.F90, src/modules/VectorField/src/VectorField_Class.F90, src/submodules/AbstractNodeField/src/AbstractNodeField_Class@SetMethods.F90, src/submodules/STScalarField/src/STScalarField_Class@SetMethods.F90, src/submodules/STVectorField/src/STVectorField_Class@DBCMethods.F90, src/submodules/STVectorField/src/STVectorField_Class@SetMethods.F90, src/submodules/ScalarField/src/ScalarField_Class@SetMethods.F90, src/submodules/VectorField/src/VectorField_Class@SetMethods.F90
- Adding Set method (by copy)
- Adding SetByFunction method
Working on issue #305
=> Updates in  NodeField

src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/submodules/AbstractKernel/CMakeLists.txt, src/submodules/AbstractKernel/src/AbstractKernel_Class@ApplyDirichletBCMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ImportTomlMethods.F90, src/submodules/ScalarField/src/ScalarField_Class@DBCMethods.F90
- Updating interface of ApplyDBC in Kernel
=> Updates in ApplyDBC in Kernel

src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/modules/AbstractNodeField/src/AbstractNodeField_Class.F90, src/modules/BlockNodeField/src/BlockNodeField_Class.F90, src/modules/STScalarField/src/STScalarField_Class.F90, src/modules/STVectorField/src/STVectorField_Class.F90, src/modules/ScalarField/src/ScalarField_Class.F90, src/modules/VectorField/src/VectorField_Class.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ApplyDirichletBCMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConstructorMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@IOMethods.F90
- Updating ApplyDBC method in AbstractKernel and NodeFields
- Adding support for external field.
- This is a work in progress
=> Updates in Kernel and NodeField

src/submodules/VTKFile/src/VTKFile_Class@ConstructorMethods.F90, src/submodules/VTKFile/src/VTKFile_Class@TagsMethods.F90
- Fixing some bugs in Initiate method
=> Updates in VTKFile_Class

src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleTanmatMethods.F90, src/submodules/AbstractNodeField/src/AbstractNodeField_Class@IOMethods.F90
- Minor updates in kernel and Abstract node field
=> Minor updates

src/modules/AbstractKernel/src/KernelAssembleSurfaceForce_Method.F90, src/submodules/AbstractBC/src/AbstractBC_Class@GetMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@SetMethods.F90
- Minor improvements in Kernels
=> Minor fixes in Kernels

src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleRHSMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConstructorMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@IOMethods.F90
=> Updates in AbstractKernel

src/modules/AbstractNodeField/src/AbstractNodeField_Class.F90, src/submodules/AbstractNodeField/src/AbstractNodeField_Class@IOMethods.F90
- fixing the issue https://github.com/easifem-fortran/classes/issues/331
- add WriteData method to export multiple field variables to the same
vtk file
=> Updates IOMethods in AbstractNodeField_Class 

src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/modules/BlockNodeField/src/BlockNodeField_Class.F90, src/modules/STScalarField/src/STScalarField_Class.F90, src/modules/STVectorField/src/STVectorField_Class.F90, src/modules/ScalarField/src/ScalarField_Class.F90, src/modules/VectorField/src/VectorField_Class.F90, src/submodules/BlockNodeField/src/BlockNodeField_Class@ConstructorMethods.F90, src/submodules/STScalarField/src/STScalarField_Class@ConstructorMethods.F90, src/submodules/STVectorField/src/STVectorField_Class@ConstructorMethods.F90, src/submodules/ScalarField/src/ScalarField_Class@ConstructorMethods.F90, src/submodules/VectorField/src/VectorField_Class@ConstructorMethods.F90
- Adding a Deallocate method to Deallocate the pointer of node field.
- ScalarFieldDeallocate
- STScalarFieldDeallocate
- VectorFieldDeallocate
- STVectorFieldDeallocate
- BlockNodeFieldDeallocate
=> Updates in NodeFields

src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/modules/MatrixField/src/MatrixField_Class.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConstructorMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@IOMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@InitiateFieldsMethods.F90, src/submodules/MatrixField/src/MatrixField_Class@ConstructorMethods.F90
- Adding Deallocate Method to MatrixField
- Adding STScalarFields and STVectorFields methods to AbstractKernel
=> Updates in MatrixField and Kernels

src/modules/AbstractMatrixField/src/AbstractMatrixField_Class.F90, src/modules/MatrixField/src/MatrixField_Class.F90, src/submodules/MatrixField/src/MatrixField_Class@GetMethods.F90
=> Updates in MatrixField

src/modules/VectorField/src/VectorField_Class.F90, src/submodules/STVectorFieldLis/src/STVectorFieldLis_Class@GetMethods.F90, src/submodules/VectorField/src/VectorField_Class@SetMethods.F90
- Adding Get method 
- Fixes issue #346 and issue #348
=> Updates in Node fields

src/modules/AbstractKernel/src/KernelScalarProperty_Method.F90, src/modules/STVectorField/src/STVectorField_Class.F90, src/submodules/STVectorField/src/STVectorField_Class@SetMethods.F90
- Minor fixes in KernelScalarProperty_Method for space-time computation
- Minor fixes in set method of STVectorField 
- Adding SetFromVectorField method to STVectorField (:wo issue #347 )
=> Vickysharma0812

src/modules/AbstractFile/src/AbstractFile_Class.F90, src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/modules/AbstractKernel/src/KernelAssembleElastoDynaMatrix_Method.F90, src/modules/AbstractKernel/src/KernelAssembleMassMatrix_Method.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@SetMethods.F90, src/submodules/STVectorField/src/STVectorField_Class@SetMethods.F90
- Updates in Kernels
- Adding SetAlgoParam method
=> Updates in Kernel

src/modules/AbstractMatrixField/src/AbstractMatrixField_Class.F90, src/modules/GmshAPI/src/GmshStructuredMesh_Class.F90, src/modules/MatrixField/src/MatrixField_Class.F90, src/submodules/MatrixField/src/MatrixField_Class@GetMethods.F90, src/submodules/MatrixField/src/MatrixField_Class@SetMethods.F90
- Adding SetFromSTMatrix
- Adding SetToSTMatrix 
- Updates in Get7 
- Fixing some bugs in GmshStructuredMesh_Class
=> Updates in MatrixField and GmshAPI

src/modules/AbstractKernel/CMakeLists.txt, src/modules/AbstractKernel/src/KernelAssembleSTElastoDynaMatrix_Method.F90, src/modules/AbstractKernel/src/KernelScalarProperty_Method.F90, src/modules/AbstractKernel/src/KernelUtility.F90, src/submodules/AbstractBC/src/AbstractBC_Class@IOMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleTanmatMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConstructorMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ImportTomlMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@MaterialMethods.F90, src/submodules/Domain/src/Domain_Class@GetMethods.F90, src/submodules/MeshSelection/src/MeshSelection_Class@GetNodeNumMethods.F90, src/submodules/MeshSelection/src/MeshSelection_Class@IOMethods.F90, src/submodules/MeshSelection/src/MeshSelection_Class@SetMethods.F90
- This PR brings several enhancements and new features in AbstractKernel class.
- Import from toml 
- Adding space time tangent matrix for elastodynamics
=> Updates in Kernel 

src/modules/AbstractNodeField/src/AbstractNodeField_Class.F90, src/submodules/AbstractNodeField/src/AbstractNodeField_Class@BlasMethods.F90
=> Updates AXPY in AbstractNodeField_Class

src/submodules/AbstractLinSolver/src/AbstractLinSolver_Class@ImportTomlMethods.F90
- Minor changes in ImportTomlMethods
=> Updates in AbstractLinSolver_Class

src/modules/RefElement/src/RefElementFactory.F90, src/submodules/AbstractFE/src/AbstractFE_Class@ConstructorMethods.F90
- change elemType to topoType
- fixing the issue #366
=> Updates in RefElement and AbstractFE_Class

src/submodules/AbstractNodeField/src/AbstractNodeField_Class@IOMethods.F90
- fixing the issue #337
- enabling to pass full name of node fields to vtk file
=> Updates WriteData in AbstractNodeField_Class

src/modules/AbstractKernel/CMakeLists.txt, src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/modules/AbstractKernel/src/KernelAssembleBodySource_Method.F90, src/modules/AbstractKernel/src/KernelAssembleDampingMatrix_Method.F90, src/modules/AbstractKernel/src/KernelAssembleDiffusionMatrix_Method.F90, src/modules/AbstractKernel/src/KernelAssembleElastoDynaMatrix_Method.F90, src/modules/AbstractKernel/src/KernelAssembleMassMatrix_Method.F90, src/modules/AbstractKernel/src/KernelAssembleSTAcousticMatrix_Method.F90, src/modules/AbstractKernel/src/KernelAssembleSTElastoDynaMatrix_Method.F90, src/modules/AbstractKernel/src/KernelAssembleStiffnessMatrix_Method.F90, src/modules/AbstractKernel/src/KernelAssembleSurfaceSource_Method.F90, src/modules/AbstractKernel/src/KernelUtility.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@AssembleTanmatMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConstructorMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@IOMethods.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@SetMethods.F90
- changing names lin~ to geo~
- adding KernelAssembleSTAcousticMatrix_Method
=> Updates in AbstractKernel_Class

src/modules/BinaryTree/CMakeLists.txt, src/modules/BinaryTree/src/BinaryTrees.F90
Adding BinaryTrees modules 
BinaryTrees module will contains all modules and utilities
=> Adding BinaryTrees Module

src/modules/AbstractKernel/src/CSDAlgorithms.F90
- adding other Bathe's methods utility
- adding importFromToml methods
- these updates are related to the  issue #376
=> Updates in CSDAlgorithms

src/modules/Mesh/CMakeLists.txt, src/modules/Mesh/src/ElemData_Class.F90, src/modules/Mesh/src/FacetData_Class.F90, src/modules/Mesh/src/Mesh_Class.F90, src/modules/Mesh/src/NodeData_Class.F90, src/submodules/Mesh/src/Mesh_Class@IOMethods.F90
Updates in Mesh_Class
- Adding ElemData_Class module
- Adding FacetData_Class module
- Adding NodeData_Class module
- Removing ElemData_, FacetData_, and NodeData_ from the Mesh_Class
=> Updates in mesh

src/modules/AbstractMesh/CMakeLists.txt, src/modules/AbstractMesh/src/AbstractMesh_Class.F90, src/modules/CMakeLists.txt, src/modules/Mesh/src/Mesh_Class.F90, src/modules/easifemClasses/src/easifemClasses.F90, src/submodules/AbstractMesh/CMakeLists.txt, src/submodules/AbstractMesh/src/AbstractMesh_Class@Methods.F90, src/submodules/CMakeLists.txt
=> Adding AbstractMesh_Class

src/modules/AbstractMesh/src/AbstractMesh_Class.F90, src/modules/Mesh/src/Mesh_Class.F90
Updates in Mesh_Class
- Making Mesh_Class as the subclass of AbstractMesh_Class.
- Getting ready for the New Mesh API
=> Updates in Mesh_Class

src/submodules/Mesh/src/Mesh_Class@IOMethods.F90
=> minor updates in mesh_class

src/modules/DynamicMesh/src/DynamicMesh_Class.F90, src/submodules/DynamicMesh/CMakeLists.txt, src/submodules/DynamicMesh/src/DynamicMesh_Class@IOMethods.F90, src/submodules/DynamicMesh/src/DynamicMesh_Class@NodeDataMethods.F90
=> adding nodeDataBinaryTree to DynamicMesh_Class

src/submodules/Mesh/src/Mesh_Class@NodeDataMethods.F90
Minor changes in Mesh_Class@NodeDataMethods
=> minor updates in mesh

src/submodules/AbstractMesh/src/AbstractMesh_Class@IOMethods.F90
- Updating AbstractMesh_Class Import method
---
<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## TL;DR
> This pull request adds new functionality to the `AbstractMesh_Class` module in the `AbstractMesh` submodule. It includes changes to the `IOMethods` submodule, specifically adding a new method `HDF5ReadMatrix` and modifying existing methods `HDF5ReadScalar` and `HDF5ReadVector`. The changes allow for reading and processing additional data from an HDF5 file.
> 
> ## What changed
> - Added `HDF5ReadMatrix` method to the `HDF5File_Method` module.
> - Modified `HDF5ReadScalar` and `HDF5ReadVector` methods in the `HDF5File_Method` module to include additional arguments.
> - Added new variables `internalNptrs` and …
=> Updating AbstractMesh_Class import

src/modules/CPUTime/src/CPUTime_Class.F90, src/submodules/AbstractKernel/src/AbstractKernel_Class@ConstructorMethods.F90, src/submodules/CPUTime/src/CPUTime_Class@Methods.F90
=> Updates in CPUTime_Class

src/modules/AbstractMesh/src/ElemData_Class.F90, src/modules/AbstractMesh/src/NodeData_Class.F90
- Adding copy methods in ElemData_Class and NodeData_Class
=> Updates in ElemData and NodeData_Class

src/modules/AbstractMesh/src/ElemData_Class.F90, src/modules/Mesh/src/Mesh_Class.F90, src/submodules/AbstractMesh/src/AbstractMesh_Class@ConstructorMethods.F90, src/submodules/AbstractMesh/src/AbstractMesh_Class@IOMethods.F90, src/submodules/AbstractMesh/src/AbstractMesh_Class@NodeDataMethods.F90, src/submodules/Mesh/src/Mesh_Class@IOMethods.F90, src/submodules/Mesh/src/Mesh_Class@NodeDataMethods.F90
- Bringing most of the code from Mesh to AbstractMesh_Class
=> Updates in AbstractMesh_Class

src/submodules/AbstractMesh/src/AbstractMesh_Class@NodeDataMethods.F90
Updating AbstractMesh_Class
This work is related to reducing the code in Mesh_Class and putting it to AbstractMesh_Class. Also, we are making InitiateNodeElements routine faster. 
---
<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## TL;DR
> This pull request introduces a change in the `AbstractMesh_Class@NodeDataMethods.F90` file. The change involves the addition of a new variable `nodewise_size` and a new parameter `chunk_size`. The `Append` method has been replaced with the `Expand` method to improve the efficiency of the code.
> 
> ## What changed
> The `obj_InitiateNodeToElements` method in the `AbstractMesh_Class@NodeDataMethods.F90` file has been modified. A new variable `nodewise_size` has been introduced to …
=> Making NodeToElements faster

src/modules/CMakeLists.txt, src/modules/Files/src/Files.F90, src/modules/PVDFile/CMakeLists.txt, src/modules/PVDFile/src/PVDFile_Class.F90, src/submodules/CMakeLists.txt, src/submodules/PVDFile/CMakeLists.txt, src/submodules/PVDFile/src/PVDFile_Class@ConstructorMethods.F90, src/submodules/PVDFile/src/PVDFile_Class@TagsMethods.F90
- adding PVDFile_Class and its methods
- fixing the issue #443
=> Implementing PVDFile_Class

src/modules/AbstractKernel/src/SDAlgorithms.F90
- adding HHT alpha and Collocation methods
- working on the issue #442
=> Updates in SDAlgorithms

src/modules/AbstractKernel/src/SDAlgorithms.F90
=> Updates SDAlgorithms

src/modules/Domain/src/Domain_Class.F90, src/submodules/Domain/src/Domain_Class@ConstructorMethods.F90
Adding meshListPoint, meshListCurve, meshListSurface, and
meshListVolume
Minor updates in constructor methods
=> Updates in Domain

src/modules/HDF5File/src/HDF5File_Method.F90
Updating read scalar method for char and string.
=> Updates in HDF5File_Method

src/modules/AbstractMesh/src/AbstractMesh_Class.F90, src/modules/Mesh/src/Mesh_Class.F90, src/submodules/AbstractMesh/CMakeLists.txt, src/submodules/AbstractMesh/src/AbstractMeshUtility.F90, src/submodules/AbstractMesh/src/AbstractMesh_Class@ConstructorMethods.F90, src/submodules/AbstractMesh/src/AbstractMesh_Class@IOMethods.F90, src/submodules/AbstractMesh/src/AbstractMesh_Class@NodeDataMethods.F90, src/submodules/AbstractMesh/src/AbstractMesh_Class@SetMethods.F90
- Improving Import Method
- Adding AbstractMeshUtility module
=> Updates in AbstractMesh

src/submodules/AbstractMesh/src/AbstractMesh_Class@IOMethods.F90
- Updates in AbstractMesh Display method
=> Updates in Mesh Display

src/submodules/AbstractMesh/src/AbstractMeshUtility.F90
- AbstractMeshUtility updating
=> Updates in AbstractMesh Import

src/modules/AbstractMesh/src/ElemData_Class.F90, src/submodules/AbstractMesh/src/AbstractMeshUtility.F90, src/submodules/AbstractMesh/src/AbstractMesh_Class@EdgeDataMethods.F90, src/submodules/AbstractMesh/src/AbstractMesh_Class@ElementDataMethods.F90, src/submodules/AbstractMesh/src/AbstractMesh_Class@FaceDataMethods.F90, src/submodules/AbstractMesh/src/AbstractMesh_Class@GetMethods.F90
Fixing a bug which is caused due to change of param names in reference element in base.
=> Fixing a bug related

src/modules/ElastoDynamics1DSTFEM/src/ElastoDynamics1DSTFEM_Class.F90, src/submodules/ElastoDynamics1DSTFEM/src/ElastoDynamics1DSTFEM_Class@Methods.F90
- adding variables to control the behavior of writeData method
- improving writeData method
=> Updates ElastoDynamics1DSTFEM_Class

src/modules/AbstractKernel/src/AbstractKernel_Class.F90, src/modules/CMakeLists.txt, src/modules/ElastoDynamics1DSDFEM/CMakeLists.txt, src/modules/ElastoDynamics1DSDFEM/src/ElastoDynamics1DSDFEM_Class.F90, src/modules/ElastoDynamics1DSTFEM/src/ElastoDynamics1DSTFEM_Class.F90, src/modules/Helmholtz1DFEM/CMakeLists.txt, src/modules/Helmholtz1DFEM/src/Helmholtz1DFEM_Class.F90, src/modules/SDAlgorithms/CMakeLists.txt, src/modules/SDAlgorithms/src/SDAlgorithms.F90, src/submodules/CMakeLists.txt, src/submodules/ElastoDynamics1DSDFEM/CMakeLists.txt, src/submodules/ElastoDynamics1DSDFEM/src/ElastoDynamics1DSDFEM_Class@Methods.F90, src/submodules/ElastoDynamics1DSTFEM/src/ElastoDynamics1DSTFEM_Class@Methods.F90, src/submodules/Helmholtz1DFEM/CMakeLists.txt, src/submodules/Helmholtz1DFEM/src/Helmholtz1DFEM_Class@Methods.F90
- adding `Helmholtz1DFEM_Class` to solve 1d Helmholtz equation with FEM.
=> Implementation Helmholtz1DFEM_Class and Elastodynamics1DSDFEM_Class

src/modules/ElastoDynamics1DSTFEM/src/ElastoDynamics1DSTFEM_Class.F90, src/submodules/ElastoDynamics1DSTFEM/src/ElastoDynamics1DSTFEM_Class@Methods.F90, src/submodules/GnuPlot/src/GnuPlot_Class@PlotMethods.F90
- adding the utilities for the error analysis
- fixing the bug in GnuPlot_Class
=> Updates in ElastoDynamics1DSTFEM_Class and GnuPlot_Class

src/submodules/ElastoDynamics1DSTFEM/src/ElastoDynamics1DSTFEM_Class@Methods.F90
- improving the importTomlUtility for material properties and element data
=> Updates in ElastoDynamics1DSTFEM_Class

src/submodules/ElastoDynamics1DSTFEM/src/ElastoDynamics1DSTFEM_Class@Methods.F90
=> updates in Elastodynamic1DSTFEM_Class

src/modules/VTKFile/src/VTKFile_Class.F90, src/submodules/AbstractNodeField/src/AbstractNodeField_Class@GetMethods.F90, src/submodules/FEDOF/src/FEDOF_Class@ConstructorMethods.F90, src/submodules/FEDOF/src/FEDOF_Class@SetSparsityMethods.F90, src/submodules/GnuPlot/src/include/colorPalettes.F90
- merge the temp branch to recover some changes that were removed for some reason.
=> Merge Shion_temp

src/modules/EasyPlplot/CMakeLists.txt, src/modules/EasyPlplot/src/EasyPlplot.F90, src/modules/PLPlot/CMakeLists.txt, src/modules/Plot/src/Plot_Method.F90, src/submodules/PLPlot/CMakeLists.txt
This pull request introduces conditional compilation and build configuration changes to enable or disable the use of PLPlot based on the `USE_PLPLOT` flag. Additionally, it includes minor fixes to licensing comments and updates to type declarations in the Fortran code.
* Modified `src/modules/EasyPlplot/CMakeLists.txt` and `src/modules/PLPlot/CMakeLists.txt` to wrap source file inclusion in an `if(USE_PLPLOT)` block, allowing PLPlot-related files to be included only when the `USE_PLPLOT` flag is set. [[1]](diffhunk://#diff-5795ffb284eca20ac14c8481e67f921c380557d607acd6da912abc3c9c9decc0L1-R23) [[2]](diffhunk://#diff-54bf4b21e9bc3c10d7602a49bd79aded80cab5d0bc8a7f553ebd80692e0080c6L1-L22)
* Updated Fortran modules (`EasyPlplot.F90`, `Plot_Method.F90`) to conditionally include the `USE …
=> Making some adjustment to compile easifem without plplot support.

src/modules/EasyPlplot/CMakeLists.txt, src/modules/EasyPlplot/src/EasyPlplot.F90, src/modules/PLPlot/CMakeLists.txt, src/modules/PLPlot/src/PLPlot_Class.F90, src/submodules/PLPlot/CMakeLists.txt, src/submodules/PLPlot/src/PLPlot_Class@BarMethods.F90, src/submodules/PLPlot/src/PLPlot_Class@ColorbarMethods.F90, src/submodules/PLPlot/src/PLPlot_Class@ConstructorMethods.F90, src/submodules/PLPlot/src/PLPlot_Class@ContourMethods.F90, src/submodules/PLPlot/src/PLPlot_Class@FillMethods.F90, src/submodules/PLPlot/src/PLPlot_Class@LinePlotMethods copy.F90, src/submodules/PLPlot/src/PLPlot_Class@LinePlotMethods.F90, src/submodules/PLPlot/src/PLPlot_Class@PlotMethods.F90, src/submodules/PLPlot/src/PLPlot_Class@QuiverMethods.F90, src/submodules/PLPlot/src/PLPlot_Class@ScatterMethods.F90, src/submodules/PLPlot/src/PLPlot_Class@SetMethods.F90, src/submodules/PLPlot/src/PLPlot_Class@SurfaceMethods.F90
Now we can compile with or without plplot. You need to select this option in easifemBase. No need to specify it in easifemClasses toml file.
This pull request introduces conditional compilation for the PLPlot module and its submodules using the `USE_PLPLOT` preprocessor directive. The changes ensure that PLPlot-related code is only included if `USE_PLPLOT` is defined, improving modularity and configurability.
* **CMake Configuration Updates:**
- Removed the `if(USE_PLPLOT)` condition from `CMakeLists.txt` files in `src/modules/EasyPlplot`, `src/modules/PLPlot`, and `src/submodules/PLPlot`. Instead, the `USE_PLPLOT` directive is now handled within the source files themselves. [[1]](diffhunk://#diff-5795ffb284eca20ac14c8481e67f921c380557d607acd6da912abc3c9c9decc0L18-L23) …
=> Compilation with or without plplot

src/submodules/GnuPlot/src/GnuPlot_Class@PlotMethods.F90
=> Updates in GnuPlot
